sudo: required

language: java

services:
  - docker

jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk10
  - openjdk8
  - openjdk9
  - openjdk10

cache:
  directories:
    - .autoconf
env:
  matrix:
    - TEST_SET="-Ptravis_e2e_skip"
    - TEST_SET="-Ptravis_e2e"
    - TEST_SET="glassfish-copyright:copyright"

install: true

script:
  - bash travis.sh $TEST_SET
